version: '3.8'

services:
  minimal-login-page:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: minimal-login-page:dev
    container_name: minimal-login-page
    ports:
      - 8080:8080
    environment:
      - HTTP_PORT=8080
      - GIN_MODE=debug
    deploy:
      restart_policy:
        condition: on-failure
