version: '3.8'

services:
  data-provider:
    build:
      context: data-provider/
      dockerfile: Dockerfile.dev
    container_name: data-provider
    ports:
      - 8080:8080
    environment:
      - HTTP_PORT=8080
      - GIN_MODE=debug
    volumes:
      - ./data-provider:/app
    deploy:
      restart_policy:
        condition: on-failure

