version: '3.8'

services:
  minimal-login-page:
    build:
      context: .
    image: minimal-login-page
    container_name: minimal-login-page
    ports:
      - 8080:8080
    environment:
      - HTTP_PORT=8080
      - GIN_MODE=release
    deploy:
      restart_policy:
        condition: on-failure

